###########
# site.title

title:    'Private Health Education Assistant Using Image Classification and RAG'
subtitle: 'CS 175: Project in AI'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md
